services:
  frontend:
    build:
      context: ./sellingOffline
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./sellingOffline-backend
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - ./sellingOffline-backend/.env
    volumes:
      - ./sellingOffline-backend/public:/app/public
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selling_offline
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
volumes:
  postgres_data: